site_name: Islandora CLAW
site_dir: site
docs_dir: docs
site_description: Documentation for Islandora CLAW

dev_addr: 'localhost:8111'
repo_url: https://github.com/kimpham54/docstest

theme: bootstrap

extra:
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    twitter: 'islandora'
